# Generated by Django 5.0 on 2024-04-09 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('classificacao', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)])),
                ('duracao', models.DurationField()),
                ('tredimenter', models.IntegerField()),
                ('reviews', models.FloatField()),
                ('specs', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('sinopse', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('realease_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
