# Generated by Django 5.0 on 2024-04-15 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_rename_specs_production_especificacoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passaport',
            fields=[
                ('number', models.CharField(max_length=100, verbose_name='Passaport Nuber')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expiration_date', models.DateField(verbose_name='Expiration Date')),
                ('ower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='producao.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
