# Generated by Django 5.0 on 2024-04-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_person_passaport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passaport',
        ),
    ]
