# Generated by Django 5.0 on 2024-04-16 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='nome',
        ),
    ]
