# Generated by Django 5.0 on 2024-04-16 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0006_remove_production_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='populadidade',
            new_name='popularidade',
        ),
    ]
