# Generated by Django 5.0 on 2024-04-16 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0007_rename_populadidade_production_popularidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='popularidade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
