# Generated by Django 5.0 on 2024-04-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0009_alter_production_nota_alter_production_popularidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='duracao',
            field=models.TimeField(),
        ),
    ]
