# Generated by Django 5.0 on 2024-04-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0008_magazine_alter_article_magazines'),
        ('producao', '0013_magazine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Magazine',
        ),
    ]
