# Generated by Django 5.0 on 2024-04-08 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='torcedores',
            field=models.IntegerField(default=0, help_text='Quantidade de torcedores', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='example',
            name='nome',
            field=models.CharField(help_text='Nome do clube', max_length=200),
        ),
    ]
