# Generated by Django 5.0 on 2024-04-15 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0002_example_torcedores_alter_example_nome'),
        ('producao', '0004_delete_passaport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passaport',
            fields=[
                ('number', models.CharField(max_length=100, verbose_name='Passaport Nuber')),
                ('expiration_date', models.DateField(verbose_name='Expiration Date')),
                ('ower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='producao.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
