# Generated by Django 5.0 on 2024-04-15 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0003_passaport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='passaport',
            name='ower',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exemplo.person'),
        ),
    ]
