# Generated by Django 5.0 on 2024-04-16 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0004_person_alter_passaport_ower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passaport',
            old_name='ower',
            new_name='owner',
        ),
    ]
